#!/usr/bin/env python3
"""Build docs/ dashboard from collected results.

Convention:
  docs/results/<variant>/<run_id>/
    - metrics.md (from extract_metrics.py)
    - metrics.csv
    - provenance.txt
    - optional viewer link file: viewer_url.txt

This script creates:
  docs/index.md
  docs/results/<variant>/index.md
"""
from __future__ import annotations
import argparse
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[2]

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", default="fast", choices=["fast","full"])
    args = ap.parse_args()

    docs = ROOT / "docs"
    res = docs / "results"
    docs.mkdir(exist_ok=True)
    res.mkdir(parents=True, exist_ok=True)

    # discover variants from manifest
    manifest = yaml.safe_load((ROOT/"manifest.yaml").read_text())
    enabled = [Path(e["variant"]).name for e in manifest.get("experiments", []) if e.get("enabled", True)]

    lines=[]
    lines.append(f"# {manifest.get('project',{}).get('title','Results Dashboard')}\n")
    lines.append("This page is auto-generated by CI.\n")
    lines.append("## Variants\n")
    for v in enabled:
        lines.append(f"- [{v}](results/{v}/index.md)")
    lines.append("\n")

    # per-variant pages
    for v in enabled:
        vdir = res / v
        vdir.mkdir(parents=True, exist_ok=True)
        runs = sorted([p for p in vdir.iterdir() if p.is_dir()], reverse=True)
        vlines=[f"# {v} results\n"]
        if not runs:
            vlines.append("No runs collected yet.\n")
        else:
            vlines.append("## Runs\n")
            for r in runs[:50]:
                vlines.append(f"- [{r.name}]({r.name}/metrics.md)")
        (vdir/"index.md").write_text("\n".join(vlines)+"\n")

    (docs/"index.md").write_text("\n".join(lines)+"\n")
    print("Wrote docs/index.md")

if __name__ == "__main__":
    main()
